#ifndef MACHINE_CSRLIST_H_INCLUDED
#define MACHINE_CSRLIST_H_INCLUDED

#define REG_CSR_MVENDORID 0xF11
#define REG_CSR_MARCHID 0xF12
#define REG_CSR_MIMPID 0xF13
#define REG_CSR_MHARTID 0xF14

#define REG_CSR_MSTATUS 0x300
#define REG_CSR_MTVEC 0x305
#define REG_CSR_MEPC 0x341
#define REG_CSR_MCAUSE 0x342

#define REG_CSR_RDCYCLE 0xc00
#define REG_CSR_RDTIME 0xc01
#define REG_CSR_RDINSTRET 0xc02
#define REG_CSR_RDCYCLEH 0xc80
#define REG_CSR_RDTIMEH 0xc81
#define REG_CSR_RDINSTRETH 0xc82

#define REG_CSR_Per_LDMISALIGNED 0xb03
#define REG_CSR_Per_STMISALIGNED 0xb04
#define REG_CSR_Per_LDSTALL 0xb05
#define REG_CSR_Per_JRSTALL 0xb06
#define REG_CSR_Per_LD 0xb07
#define REG_CSR_Per_ST 0xb08
#define REG_CSR_Per_JUMP 0xb09
#define REG_CSR_Per_BRANCH 0xb0a
#define REG_CSR_Per_BTAKEN 0xb0b
#define REG_CSR_Per_CSRWASTE 0xb0c

#define INTR_RESET_ADDR 0x80
#define INTR_ILLEGAL_ADDR 0x84
#define INTR_ECALL_ADDR 0x88


#endif // MACHINE_CSRLIST_H_INCLUDED
