#!/bin/bash
./run_compliancetest_top ../tests/compliance/rv32i/I-ADDI-01.elf    ../tests/compliance/rv32i/references/I-ADDI-01    > I-addi.log
./run_compliancetest_top ../tests/compliance/rv32i/I-ADD-01.elf     ../tests/compliance/rv32i/references/I-ADD-01     > I-add.log
./run_compliancetest_top ../tests/compliance/rv32i/I-ANDI-01.elf    ../tests/compliance/rv32i/references/I-ANDI-01    > I-andi.log
./run_compliancetest_top ../tests/compliance/rv32i/I-AND-01.elf     ../tests/compliance/rv32i/references/I-AND-01     > I-and.log
./run_compliancetest_top ../tests/compliance/rv32i/I-AUIPC-01.elf   ../tests/compliance/rv32i/references/I-AUIPC-01   > I-auipc.log
./run_compliancetest_top ../tests/compliance/rv32i/I-BEQ-01.elf     ../tests/compliance/rv32i/references/I-BEQ-01     > I-beq.log
./run_compliancetest_top ../tests/compliance/rv32i/I-BGEU-01.elf    ../tests/compliance/rv32i/references/I-BGEU-01    > I-bgeu.log
./run_compliancetest_top ../tests/compliance/rv32i/I-BGE-01.elf     ../tests/compliance/rv32i/references/I-BGE-01     > I-bge.log
./run_compliancetest_top ../tests/compliance/rv32i/I-BLTU-01.elf    ../tests/compliance/rv32i/references/I-BLTU-01    > I-bltu.log
./run_compliancetest_top ../tests/compliance/rv32i/I-BLT-01.elf     ../tests/compliance/rv32i/references/I-BLT-01     > I-blt.log
./run_compliancetest_top ../tests/compliance/rv32i/I-BNE-01.elf     ../tests/compliance/rv32i/references/I-BNE-01     > I-bne.log
./run_compliancetest_top ../tests/compliance/rv32i/I-JALR-01.elf    ../tests/compliance/rv32i/references/I-JALR-01    > I-jalr.log
./run_compliancetest_top ../tests/compliance/rv32i/I-JAL-01.elf     ../tests/compliance/rv32i/references/I-JAL-01     > I-jal.log
./run_compliancetest_top ../tests/compliance/rv32i/I-LBU-01.elf     ../tests/compliance/rv32i/references/I-LBU-01 2030    > I-lbu.log
./run_compliancetest_top ../tests/compliance/rv32i/I-LB-01.elf      ../tests/compliance/rv32i/references/I-LB-01  2030    > I-lb.log
./run_compliancetest_top ../tests/compliance/rv32i/I-LHU-01.elf     ../tests/compliance/rv32i/references/I-LHU-01 2030    > I-lhu.log
./run_compliancetest_top ../tests/compliance/rv32i/I-LH-01.elf      ../tests/compliance/rv32i/references/I-LH-01  2030    > I-lh.log
./run_compliancetest_top ../tests/compliance/rv32i/I-LUI-01.elf     ../tests/compliance/rv32i/references/I-LUI-01     > I-lui.log
./run_compliancetest_top ../tests/compliance/rv32i/I-LW-01.elf      ../tests/compliance/rv32i/references/I-LW-01  2030    > I-lw.log
./run_compliancetest_top ../tests/compliance/rv32i/I-ORI-01.elf     ../tests/compliance/rv32i/references/I-ORI-01     > I-ori.log
./run_compliancetest_top ../tests/compliance/rv32i/I-OR-01.elf      ../tests/compliance/rv32i/references/I-OR-01      > I-or.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SB-01.elf      ../tests/compliance/rv32i/references/I-SB-01      > I-sb.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SH-01.elf      ../tests/compliance/rv32i/references/I-SH-01      > I-sh.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SLLI-01.elf    ../tests/compliance/rv32i/references/I-SLLI-01    > I-slli.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SLL-01.elf     ../tests/compliance/rv32i/references/I-SLL-01     > I-sll.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SLTIU-01.elf   ../tests/compliance/rv32i/references/I-SLTIU-01   > I-sltiu.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SLTI-01.elf    ../tests/compliance/rv32i/references/I-SLTI-01    > I-slti.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SLTU-01.elf    ../tests/compliance/rv32i/references/I-SLTU-01    > I-sltu.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SLT-01.elf     ../tests/compliance/rv32i/references/I-SLT-01     > I-slt.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SRAI-01.elf    ../tests/compliance/rv32i/references/I-SRAI-01    > I-srai.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SRA-01.elf     ../tests/compliance/rv32i/references/I-SRA-01     > I-sra.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SRLI-01.elf    ../tests/compliance/rv32i/references/I-SRLI-01    > I-srli.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SRL-01.elf     ../tests/compliance/rv32i/references/I-SRL-01     > I-srl.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SUB-01.elf     ../tests/compliance/rv32i/references/I-SUB-01     > I-sub.log
./run_compliancetest_top ../tests/compliance/rv32i/I-SW-01.elf      ../tests/compliance/rv32i/references/I-SW-01      > I-sw.log
./run_compliancetest_top ../tests/compliance/rv32i/I-XORI-01.elf    ../tests/compliance/rv32i/references/I-XORI-01    > I-xori.log
./run_compliancetest_top ../tests/compliance/rv32i/I-XOR-01.elf     ../tests/compliance/rv32i/references/I-XOR-01     > I-xor.log
./run_compliancetest_top ../tests/compliance/rv32i/I-DELAY_SLOTS-01.elf     ../tests/compliance/rv32i/references/I-DELAY_SLOTS-01     > I-DELAY_SLOTS.log
./run_compliancetest_top ../tests/compliance/rv32i/I-EBREAK-01.elf     ../tests/compliance/rv32i/references/I-EBREAK-01     > I-EBREAK.log
./run_compliancetest_top ../tests/compliance/rv32i/I-ECALL-01.elf     ../tests/compliance/rv32i/references/I-ECALL-01     > I-ECALL.log
./run_compliancetest_top ../tests/compliance/rv32i/I-ENDIANESS-01.elf     ../tests/compliance/rv32i/references/I-ENDIANESS-01 2010    > I-ENDIANESS.log
./run_compliancetest_top ../tests/compliance/rv32i/I-IO.elf     ../tests/compliance/rv32i/references/I-IO 2030    > I-IO.log
./run_compliancetest_top ../tests/compliance/rv32i/I-MISALIGN_JMP-01.elf     ../tests/compliance/rv32i/references/I-MISALIGN_JMP-01     > I-MISALIGN_JMP.log
./run_compliancetest_top ../tests/compliance/rv32i/I-MISALIGN_LDST-01.elf     ../tests/compliance/rv32i/references/I-MISALIGN_LDST-01 2010    > I-MISALIGN_LDST.log
./run_compliancetest_top ../tests/compliance/rv32i/I-NOP-01.elf     ../tests/compliance/rv32i/references/I-NOP-01     > I-NOP.log
./run_compliancetest_top ../tests/compliance/rv32i/I-RF_size-01.elf     ../tests/compliance/rv32i/references/I-RF_size-01     > I-RF_size.log
./run_compliancetest_top ../tests/compliance/rv32i/I-RF_width-01.elf     ../tests/compliance/rv32i/references/I-RF_width-01     > I-RF_width.log
./run_compliancetest_top ../tests/compliance/rv32i/I-RF_x0-01.elf     ../tests/compliance/rv32i/references/I-RF_x0-01 2010    > I-RF_x0.log
